"""empty message

Revision ID: 19c37e1abd2b
Revises: eb40b6c7737d
Create Date: 2025-09-08 23:17:00.570490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c37e1abd2b'
down_revision = 'eb40b6c7737d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deadline_type', sa.String(length=120), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=False),
    sa.Column('deadline_hour', sa.Time(), nullable=False),
    sa.Column('priority', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deadlines')
    # ### end Alembic commands ###
