"""empty message

Revision ID: 3d55d7b345c8
Revises: 4c7ef903df58
Create Date: 2025-09-17 00:58:16.305911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d55d7b345c8'
down_revision = '4c7ef903df58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.alter_column('url_img',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.alter_column('url_img',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
