"""empty message

Revision ID: 4af4331d1152
Revises: 
Create Date: 2025-09-17 17:41:51.280900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af4331d1152'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('url_img', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courtfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=255), nullable=False),
    sa.Column('court', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deadline_type', sa.String(length=120), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=False),
    sa.Column('deadline_hour', sa.Time(), nullable=False),
    sa.Column('priority', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('url_route', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lawyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('url_img', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='paymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('means', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment_courtfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('courtfile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['courtfile_id'], ['courtfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_courtfile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_courtfile_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_courtfile_courtfile_id'), ['courtfile_id'], unique=False)

    op.create_table('client_courtfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('courtfile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['courtfile_id'], ['courtfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_courtfile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_courtfile_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_courtfile_courtfile_id'), ['courtfile_id'], unique=False)

    op.create_table('courtfile_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courtfile_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courtfile_id'], ['courtfile.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courtfile_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courtfile_document_courtfile_id'), ['courtfile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courtfile_document_document_id'), ['document_id'], unique=False)

    op.create_table('deadline_courtfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deadline_id', sa.Integer(), nullable=False),
    sa.Column('courtfile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courtfile_id'], ['courtfile.id'], ),
    sa.ForeignKeyConstraint(['deadline_id'], ['deadlines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deadline_courtfile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deadline_courtfile_courtfile_id'), ['courtfile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deadline_courtfile_deadline_id'), ['deadline_id'], unique=False)

    op.create_table('lawyer_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lawyer_client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lawyer_client_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lawyer_client_lawyer_id'), ['lawyer_id'], unique=False)

    op.create_table('lawyer_courtfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('courtfile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courtfile_id'], ['courtfile.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lawyer_courtfile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lawyer_courtfile_courtfile_id'), ['courtfile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lawyer_courtfile_lawyer_id'), ['lawyer_id'], unique=False)

    op.create_table('payment_courtfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('courtfile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courtfile_id'], ['courtfile.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_courtfile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_courtfile_courtfile_id'), ['courtfile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_courtfile_payment_id'), ['payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_courtfile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_courtfile_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_courtfile_courtfile_id'))

    op.drop_table('payment_courtfile')
    with op.batch_alter_table('lawyer_courtfile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lawyer_courtfile_lawyer_id'))
        batch_op.drop_index(batch_op.f('ix_lawyer_courtfile_courtfile_id'))

    op.drop_table('lawyer_courtfile')
    with op.batch_alter_table('lawyer_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lawyer_client_lawyer_id'))
        batch_op.drop_index(batch_op.f('ix_lawyer_client_client_id'))

    op.drop_table('lawyer_client')
    with op.batch_alter_table('deadline_courtfile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deadline_courtfile_deadline_id'))
        batch_op.drop_index(batch_op.f('ix_deadline_courtfile_courtfile_id'))

    op.drop_table('deadline_courtfile')
    with op.batch_alter_table('courtfile_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courtfile_document_document_id'))
        batch_op.drop_index(batch_op.f('ix_courtfile_document_courtfile_id'))

    op.drop_table('courtfile_document')
    with op.batch_alter_table('client_courtfile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_courtfile_courtfile_id'))
        batch_op.drop_index(batch_op.f('ix_client_courtfile_client_id'))

    op.drop_table('client_courtfile')
    with op.batch_alter_table('appointment_courtfile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_courtfile_courtfile_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_courtfile_appointment_id'))

    op.drop_table('appointment_courtfile')
    op.drop_table('payment')
    op.drop_table('lawyer')
    op.drop_table('document')
    op.drop_table('deadlines')
    op.drop_table('courtfile')
    op.drop_table('client')
    op.drop_table('appointment')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
