"""empty message

Revision ID: 764d1bc00a8b
Revises: f27e4ae0ea1a
Create Date: 2025-09-15 23:27:03.650031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764d1bc00a8b'
down_revision = 'f27e4ae0ea1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='paymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('means', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_courtfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('courtfile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courtfile_id'], ['courtfile.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_courtfile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_courtfile_courtfile_id'), ['courtfile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_courtfile_payment_id'), ['payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_courtfile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_courtfile_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_courtfile_courtfile_id'))

    op.drop_table('payment_courtfile')
    op.drop_table('payment')
    # ### end Alembic commands ###
