"""empty message

Revision ID: 85a8b5a432da
Revises: 3883f5b2f61a
Create Date: 2025-09-25 23:07:41.231136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a8b5a432da'
down_revision = '3883f5b2f61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courtfile_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('next_steps', sa.JSON(), nullable=True),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("urgency in ('low','medium','high','urgent')", name='ck_ai_suggestions_urgency'),
    sa.ForeignKeyConstraint(['courtfile_id'], ['courtfile.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['lawyer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_suggestions_source_hash'), ['source_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_suggestions_source_hash'))

    op.drop_table('ai_suggestions')
    # ### end Alembic commands ###
