"""empty message

Revision ID: dea3f6b0dfeb
Revises: a9e5b2057313
Create Date: 2025-09-12 16:10:46.549955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea3f6b0dfeb'
down_revision = 'a9e5b2057313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courtfile_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courtfile_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courtfile_id'], ['courtfile.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courtfile_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courtfile_document_courtfile_id'), ['courtfile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courtfile_document_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courtfile_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courtfile_document_document_id'))
        batch_op.drop_index(batch_op.f('ix_courtfile_document_courtfile_id'))

    op.drop_table('courtfile_document')
    # ### end Alembic commands ###
