"""empty message

Revision ID: eb40b6c7737d
Revises: b107760847b8
Create Date: 2025-09-07 21:07:15.091042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb40b6c7737d'
down_revision = 'b107760847b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))

    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
