export const JURISDICCIONES_PJN = [
    'CSJ - Corte Suprema de Justicia de la Nación', 'CIV - Cámara Nacional de Apelaciones en lo Civil', 'CAF - Cámara Nacional de Apelaciones en lo Contencioso Administrativo Federal',
    'CCF - Cámara Nacional de Apelaciones en lo Civil y Comercial Federal', 'CNE - Cámara Nacional Electoral', 'CSS - Cámara Federal de la Seguridad Social',
    'CPE - Cámara Nacional de Apelaciones en lo Penal Económico', 'CNT - Cámara Nacional de Apelaciones del Trabajo', 'CFP - Cámara Criminal y Correccional Federal',
    'CCO - Cámara Nacional de Apelaciones en lo Criminal y Correccional', 'COM - Cámara Nacional de Apelaciones en lo Comercial', 'CPF - Cámara Federal de Casación Penal',
    'CPN - Cámara Nacional de Casación Penal', 'FBB - Justicia Federal de Bahía Blanca', 'FCR - Justicia Federal de Comodoro Rivadavia', 'FCB - Justicia Federal de Córdoba',
    'FCT - Justicia Federal de Corrientes', 'FGR - Justicia Federal de General Roca', 'FLP - Justicia Federal de La Plata', 'FMP - Justicia Federal de Mar del Plata',
    'FMZ - Justicia Federal de Mendoza', 'FPO - Justicia Federal de Posadas', 'FPA - Justicia Federal de Paraná', 'FRE - Justicia Federal de Resistencia',
    'FSA - Justicia Federal de Salta', 'FRO - Justicia Federal de Rosario', 'FSM - Justicia Federal de San Martín', 'FTU - Justicia Federal de Tucumán'
];

export const JUZGADOS_POR_JURISDICCION = {
    'CSJ - Corte Suprema de Justicia de la Nación': [
        'Corte Suprema de Justicia de la Nación'
    ],
    'CIV - Cámara Nacional de Apelaciones en lo Civil': [
        'Cámara Nacional de Apelaciones en lo Civil',
        'Juzgado Nacional de Primera Instancia en lo Civil N° 1',
        'Juzgado Nacional de Primera Instancia en lo Civil N° 2',
        'Juzgado Nacional de Primera Instancia en lo Civil N° 3',
        'Juzgado Nacional de Primera Instancia en lo Civil N° 4',
        'Juzgado Nacional de Primera Instancia en lo Civil N° 5',
        'Juzgado Nacional de Primera Instancia en lo Civil N° 6',
        'Juzgado Nacional de Primera Instancia en lo Civil N° 7',
        'Juzgado Nacional de Primera Instancia en lo Civil N° 8',
        'Juzgado Nacional de Primera Instancia en lo Civil N° 9',
        'Juzgado Nacional de Primera Instancia en lo Civil N° 10'
    ],
    'CAF - Cámara Nacional de Apelaciones en lo Contencioso Administrativo Federal': [
        'Cámara Nacional de Apelaciones en lo Contencioso Administrativo Federal',
        'Juzgado Contencioso Administrativo Federal N° 1',
        'Juzgado Contencioso Administrativo Federal N° 2',
        'Juzgado Contencioso Administrativo Federal N° 3',
        'Juzgado Contencioso Administrativo Federal N° 4',
        'Juzgado Contencioso Administrativo Federal N° 5',
        'Juzgado Contencioso Administrativo Federal N° 6',
        'Juzgado Contencioso Administrativo Federal N° 7',
        'Juzgado Contencioso Administrativo Federal N° 8',
        'Juzgado Contencioso Administrativo Federal N° 9',
        'Juzgado Contencioso Administrativo Federal N° 10',
        'Juzgado Contencioso Administrativo Federal N° 11',
        'Juzgado Contencioso Administrativo Federal N° 12',
        'Juzgado Federal de Ejecuciones Fiscales y Tributario N° 1',
        'Juzgado Federal de Ejecuciones Fiscales y Tributario N° 2',
        'Juzgado Federal de Ejecuciones Fiscales y Tributario N° 3',
        'Juzgado Federal de Ejecuciones Fiscales y Tributario N° 4',
        'Juzgado Federal de Ejecuciones Fiscales y Tributario N° 5',
        'Juzgado Federal de Ejecuciones Fiscales y Tributario N° 6',
    ],
    'CCF - Cámara Nacional de Apelaciones en lo Civil y Comercial Federal': [
        'Cámara Nacional de Apelaciones en lo Civil y Comercial Federal',
        'Juzgado Nacional de Primera Instancia en lo Civil y Comercial Federal N° 1',
        'Juzgado Nacional de Primera Instancia en lo Civil y Comercial Federal N° 2',
        'Juzgado Nacional de Primera Instancia en lo Civil y Comercial Federal N° 3',
        'Juzgado Nacional de Primera Instancia en lo Civil y Comercial Federal N° 4',
        'Juzgado Nacional de Primera Instancia en lo Civil y Comercial Federal N° 5',
        'Juzgado Nacional de Primera Instancia en lo Civil y Comercial Federal N° 6'
    ],
    'CNE - Cámara Nacional Electoral': [
        'Cámara Nacional Electoral',
        'Juzgado Nacional Electoral'
    ],
    'CSS - Cámara Federal de la Seguridad Social': [
        'Cámara Federal de la Seguridad Social',
        'Juzgado Nacional de la Seguridad Social N° 1',
        'Juzgado Nacional de la Seguridad Social N° 2',
        'Juzgado Nacional de la Seguridad Social N° 3',
        'Juzgado Nacional de la Seguridad Social N° 4',
        'Juzgado Nacional de la Seguridad Social N° 5'
    ],
    'CPE - Cámara Nacional de Apelaciones en lo Penal Económico': [
        'Cámara Nacional de Apelaciones en lo Penal Económico',
        'Juzgado Nacional en lo Penal Económico N° 1',
        'Juzgado Nacional en lo Penal Económico N° 2',
        'Juzgado Nacional en lo Penal Económico N° 3',
        'Juzgado Nacional en lo Penal Económico N° 4',
        'Juzgado Nacional en lo Penal Económico N° 5',
        'Juzgado Nacional de la Seguridad Social N° 6',
        'Juzgado Nacional de la Seguridad Social N° 7',
        'Juzgado Nacional de la Seguridad Social N° 8',
        'Juzgado Nacional de la Seguridad Social N° 9',
        'Juzgado Nacional de la Seguridad Social N° 10',
        'Juzgado Nacional de la Seguridad Social N° 11',
        'Tribunal Oral en lo Penal Económico N° 1',
        'Tribunal Oral en lo Penal Económico N° 2',
        'Tribunal Oral en lo Penal Económico N° 3',
        'Tribunal Oral en lo Penal Económico N° 4'
    ],
    'CNT - Cámara Nacional de Apelaciones del Trabajo': [
        'Cámara Nacional de Apelaciones del Trabajo',
        'Juzgado Nacional del Trabajo N° 1',
        'Juzgado Nacional del Trabajo N° 2',
        'Juzgado Nacional del Trabajo N° 3',
        'Juzgado Nacional del Trabajo N° 4',
        'Juzgado Nacional del Trabajo N° 5',
        'Juzgado Nacional del Trabajo N° 6',
        'Juzgado Nacional del Trabajo N° 7',
        'Juzgado Nacional del Trabajo N° 8',
        'Juzgado Nacional del Trabajo N° 9',
        'Juzgado Nacional del Trabajo N° 10',
        'Juzgado Nacional del Trabajo N° 11',
        'Juzgado Nacional del Trabajo N° 12',
        'Juzgado Nacional del Trabajo N° 13',
        'Juzgado Nacional del Trabajo N° 14',
        'Juzgado Nacional del Trabajo N° 15',
        'Juzgado Nacional del Trabajo N° 16',
        'Juzgado Nacional del Trabajo N° 17',
        'Juzgado Nacional del Trabajo N° 18',
        'Juzgado Nacional del Trabajo N° 19',
        'Juzgado Nacional del Trabajo N° 20',
        'Juzgado Nacional del Trabajo N° 21',
        'Juzgado Nacional del Trabajo N° 22',
        'Juzgado Nacional del Trabajo N° 23',
        'Juzgado Nacional del Trabajo N° 24',
        'Juzgado Nacional del Trabajo N° 25',
        'Juzgado Nacional del Trabajo N° 26',
        'Juzgado Nacional del Trabajo N° 27',
        'Juzgado Nacional del Trabajo N° 28',
        'Juzgado Nacional del Trabajo N° 29',
        'Juzgado Nacional del Trabajo N° 30',
        'Juzgado Nacional del Trabajo N° 31',
        'Juzgado Nacional del Trabajo N° 32',
        'Juzgado Nacional del Trabajo N° 33',
        'Juzgado Nacional del Trabajo N° 34',
        'Juzgado Nacional del Trabajo N° 35',
        'Juzgado Nacional del Trabajo N° 36',
        'Juzgado Nacional del Trabajo N° 37',
        'Juzgado Nacional del Trabajo N° 38',
        'Juzgado Nacional del Trabajo N° 39',
        'Juzgado Nacional del Trabajo N° 40',
        'Juzgado Nacional del Trabajo N° 41',
        'Juzgado Nacional del Trabajo N° 42',
        'Juzgado Nacional del Trabajo N° 43',
        'Juzgado Nacional del Trabajo N° 44',
        'Juzgado Nacional del Trabajo N° 45',
        'Juzgado Nacional del Trabajo N° 46',
        'Juzgado Nacional del Trabajo N° 47',
        'Juzgado Nacional del Trabajo N° 48',
        'Juzgado Nacional del Trabajo N° 49',
        'Juzgado Nacional del Trabajo N° 50'
    ],
    'CFP - Cámara Criminal y Correccional Federal': [
        'Cámara Criminal y Correccional Federal',
        'Juzgado Nacional en lo Criminal y Correccional Federal N° 1',
        'Juzgado Nacional en lo Criminal y Correccional Federal N° 2',
        'Juzgado Nacional en lo Criminal y Correccional Federal N° 3',
        'Juzgado Nacional en lo Criminal y Correccional Federal N° 4',
        'Juzgado Nacional en lo Criminal y Correccional Federal N° 5',
        'Juzgado Nacional en lo Criminal y Correccional Federal N° 6',
        'Juzgado Nacional en lo Criminal y Correccional Federal N° 7',
        'Juzgado Nacional en lo Criminal y Correccional Federal N° 8',
        'Juzgado Nacional en lo Criminal y Correccional Federal N° 9',
        'Juzgado Nacional en lo Criminal y Correccional Federal N° 10',
        'Juzgado Nacional en lo Criminal y Correccional Federal N° 11',
        'Juzgado Nacional en lo Criminal y Correccional Federal N° 12',
        'Tribunal Oral en lo Criminal y Correccional Federal N° 1',
        'Tribunal Oral en lo Criminal y Correccional Federal N° 2',
        'Tribunal Oral en lo Criminal y Correccional Federal N° 3',
        'Tribunal Oral en lo Criminal y Correccional Federal N° 4',
        'Tribunal Oral en lo Criminal y Correccional Federal N° 5',
        'Tribunal Oral en lo Criminal y Correccional Federal N° 6',
        'Tribunal Oral en lo Criminal y Correccional Federal N° 7',
        'Tribunal Oral en lo Criminal y Correccional Federal N° 8',
    ],
    'CCO - Cámara Nacional de Apelaciones en lo Criminal y Correccional': [
        'Cámara Nacional de Apelaciones en lo Criminal y Correccional',
        'Juzgado Nacional en lo Criminal y Correccional N° 1',
        'Juzgado Nacional en lo Criminal y Correccional N° 2',
        'Juzgado Nacional en lo Criminal y Correccional N° 3',
        'Juzgado Nacional en lo Criminal y Correccional N° 4',
        'Juzgado Nacional en lo Criminal y Correccional N° 5',
        'Juzgado Nacional en lo Criminal y Correccional N° 6',
        'Juzgado Nacional en lo Criminal y Correccional N° 7',
        'Juzgado Nacional en lo Criminal y Correccional N° 8',
        'Juzgado Nacional en lo Criminal y Correccional N° 9',
        'Juzgado Nacional en lo Criminal y Correccional N° 10',
        'Juzgado Nacional en lo Criminal y Correccional N° 11',
        'Juzgado Nacional en lo Criminal y Correccional N° 12',
        'Juzgado Nacional en lo Criminal y Correccional N° 13',
        'Juzgado Nacional en lo Criminal y Correccional N° 14',
        'Juzgado Nacional en lo Criminal y Correccional N° 15',
        'Juzgado Nacional en lo Criminal y Correccional N° 16',
        'Juzgado Nacional en lo Criminal y Correccional N° 17',
        'Juzgado Nacional en lo Criminal y Correccional N° 18',
        'Juzgado Nacional en lo Criminal y Correccional N° 19',
        'Juzgado Nacional en lo Criminal y Correccional N° 20',
        'Juzgado Nacional en lo Criminal y Correccional N° 21',
        'Juzgado Nacional en lo Criminal y Correccional N° 22',
        'Juzgado Nacional en lo Criminal y Correccional N° 23',
        'Juzgado Nacional en lo Criminal y Correccional N° 24',
        'Juzgado Nacional en lo Criminal y Correccional N° 25',
        'Juzgado Nacional en lo Criminal y Correccional N° 26',
        'Juzgado Nacional en lo Criminal y Correccional N° 27',
        'Juzgado Nacional en lo Criminal y Correccional N° 28',
        'Juzgado Nacional en lo Criminal y Correccional N° 29',
        'Juzgado Nacional en lo Criminal y Correccional N° 30',
        'Juzgado Nacional en lo Criminal y Correccional N° 31',
        'Juzgado Nacional en lo Criminal y Correccional N° 32',
        'Juzgado Nacional en lo Criminal y Correccional N° 33',
        'Juzgado Nacional en lo Criminal y Correccional N° 34',
        'Juzgado Nacional en lo Criminal y Correccional N° 35',
        'Juzgado Nacional en lo Criminal y Correccional N° 36',
        'Juzgado Nacional en lo Criminal y Correccional N° 37',
        'Juzgado Nacional en lo Criminal y Correccional N° 38',
        'Juzgado Nacional en lo Criminal y Correccional N° 39',
        'Juzgado Nacional en lo Criminal y Correccional N° 40',
        'Juzgado Nacional en lo Criminal y Correccional N° 41',
        'Juzgado Nacional en lo Criminal y Correccional N° 42',
        'Juzgado Nacional en lo Criminal y Correccional N° 43',
        'Juzgado Nacional en lo Criminal y Correccional N° 44',
        'Juzgado Nacional en lo Criminal y Correccional N° 45',
        'Juzgado Nacional en lo Criminal y Correccional N° 46',
        'Juzgado Nacional en lo Criminal y Correccional N° 47',
        'Juzgado Nacional en lo Criminal y Correccional N° 48',
        'Juzgado Nacional en lo Criminal y Correccional N° 49',
        'Juzgado Nacional en lo Criminal y Correccional N° 50',
        'Juzgado Nacional en lo Criminal y Correccional N° 51',
        'Juzgado Nacional en lo Criminal y Correccional N° 52'
    ],
    'COM - Cámara Nacional de Apelaciones en lo Comercial': [
        'Cámara Nacional de Apelaciones en lo Comercial',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 1',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 2',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 3',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 4',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 5',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 6',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 7',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 8',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 9',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 10',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 11',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 12',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 13',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 14',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 15',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 16',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 17',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 18',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 19',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 20',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 21',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 22',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 23',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 24',
        'Juzgado Nacional de Primera Instancia en lo Comercial N° 25'
    ],
    'CPF - Cámara Federal de Casación Penal': [
        'Cámara Federal de Casación Penal'
    ],
    'CPN - Cámara Nacional de Casación Penal': [
        'Cámara Nacional de Casación Penal'
    ],
    'FBB - Justicia Federal de Bahía Blanca': [
        'Cámara Federal de Apelaciones de Bahía Blanca',
        'Juzgado Federal de Bahía Blanca N° 1',
        'Juzgado Federal de Bahía Blanca N° 2',
        'Juzgado Federal de Santa Rosa'
    ],
    'FCR - Justicia Federal de Comodoro Rivadavia': [
        'Cámara Federal de Apelaciones de Comodoro Rivadavia',
        'Juzgado Federal de Comodoro Rivadavia',
        'Juzgado Federal de Rawson NRO. 1',
        'Juzgado Federal de Rawson NRO. 2',
        'Juzgado Federal de Río Gallegos',
        'Juzgado Federal de Primera Instancia de Ushuaia',
        'Juzgado Federal de Río Grande',
        'Juzgado Federal de Caleta Olivia',
        'Juzgado Federal de Esquel',
        'Tribunal Oral en lo Criminal Federal de Comodoro Rivadavia',
        'Tribunal Oral en lo Criminal Federal de Santa Cruz',
        'Tribunal Oral en lo Criminal Federal de Tierra del Fuego, Antártida e Islas'
    ],
    'FCB - Justicia Federal de Córdoba': [
        'Cámara Federal de Apelaciones de Córdoba',
        'Juzgado Federal de Córdoba N° 1',
        'Juzgado Federal de Córdoba N° 2',
        'Juzgado Federal de Córdoba N° 3',
        'Juzgado Federal de Instrucción de Córdoba N° 1',
        'Juzgado Federal de Instrucción de Córdoba N° 2',
        'Juzgado Federal de Bell Ville',
        'Juzgado Federal de Río Cuarto',
        'Juzgado Federal de Villa María',
        'Juzgado Federal de La Rioja',
        'Juzgado Federal de San Francisco'
    ],
    'FCT - Justicia Federal de Corrientes': [
        'Cámara Federal de Apelaciones de Corrientes',
        'Juzgado Federal de Corrientes N° 1',
        'Juzgado Federal de Corrientes N° 2',
        'Juzgado Federal de Paso de los Libres',
        'Juzgado Federal de Goya',
        'Tribunal Oral en lo Criminal Federal de Corrientes'
    ],
    'FGR - Justicia Federal de General Roca': [
        'Cámara Federal de Apelaciones de General Roca',
        'Juzgado Federal de General Roca',
        'Juzgado Federal de San Carlos de Bariloche',
        'Juzgado Federal de Viedma',
        'Juzgado Federal de Zapala',
        'Juzgado Federal de Neuquén N° 1',
        'Juzgado Federal de Neuquén N° 2',
        'Tribunal Oral en lo Criminal Federal de General Roca',
        'Tribunal Oral en lo Criminal Federal de Neuquén'
    ],
    'FLP - Justicia Federal de La Plata': [
        'Cámara Federal de Apelaciones de La Plata',
        'Juzgado Federal de La Plata N° 1 - Penal y Electoral',
        'Juzgado Federal de La Plata N° 2 - Civil, Comercial y Contencioso Administrativo',
        'Juzgado Federal de La Plata N° 3 - Penal',
        'Juzgado Federal de La Plata N° 4 - Civil y Comercial',
        'Juzgado Federal en lo Criminal y Correccional de Lomas de Zamora N° 1',
        'Juzgado Federal en lo Criminal y Correccional de Lomas de Zamora N° 2',
        'Juzgado Federal de Lomas de Zamora N° 3 - Civil, Comercial y Contencioso Administrativo',
        'Juzgado Federal de Quilmes',
        'Juzgado Federal de Junín',
        'Juzgado Federal de Pehuajó',
        'Tribunal Oral en lo Criminal Federal de La Plata N° 1',
        'Tribunal Oral en lo Criminal Federal de La Plata N° 2'
    ],
    'FMP - Justicia Federal de Mar del Plata': [
        'Cámara Federal de Apelaciones de Mar del Plata',
        'Juzgado Federal de Mar del Plata N° 1 - Penal',
        'Juzgado Federal de Mar del Plata N° 2 - Civil, Comercial y Laboral',
        'Juzgado Federal de Mar del Plata N° 3',
        'Juzgado Federal de Mar del Plata N° 4',
        'Juzgado Federal de Azul N° 1',
        'Juzgado Federal de Azul N° 2',
        'Juzgado Federal de Dolores',
        'Juzgado Federal de Necochea',
        'Tribunal Oral en lo Criminal Federal de Mar del Plata'
    ],
    'FMZ - Justicia Federal de Mendoza': [
        'Cámara Federal de Apelaciones de Mendoza',
        'Juzgado Federal de Mendoza N° 1',
        'Juzgado Federal de Mendoza N° 2',
        'Juzgado Federal de Instrucción de Mendoza N° 1',
        'Juzgado Federal de Instrucción de Mendoza N° 2'
    ],
    'FPO - Justicia Federal de Posadas': [
        'Cámara Federal de Apelaciones de Posadas',
        'Juzgado Federal de Posadas N° 1',
        'Juzgado Federal de Instrucción de Posadas N° 1'
    ],
    'FPA - Justicia Federal de Paraná': [
        'Cámara Federal de Apelaciones de Paraná',
        'Juzgado Federal de Paraná N° 1',
        'Juzgado Federal de Instrucción de Paraná N° 1'
    ],
    'FRE - Justicia Federal de Resistencia': [
        'Cámara Federal de Apelaciones de Resistencia',
        'Juzgado Federal de Resistencia N° 1',
        'Juzgado Federal de Instrucción de Resistencia N° 1'
    ],
    'FSA - Justicia Federal de Salta': [
        'Cámara Federal de Apelaciones de Salta',
        'Juzgado Federal de Salta N° 1',
        'Juzgado Federal de Instrucción de Salta N° 1'
    ],
    'FRO - Justicia Federal de Rosario': [
        'Cámara Federal de Apelaciones de Rosario',
        'Juzgado Federal de Rosario N° 1',
        'Juzgado Federal de Rosario N° 2',
        'Juzgado Federal de Instrucción de Rosario N° 1',
        'Juzgado Federal de Instrucción de Rosario N° 2'
    ],
    'FSM - Justicia Federal de San Martín': [
        'Cámara Federal de Apelaciones de San Martín',
        'Juzgado Federal de San Martín N° 1',
        'Juzgado Federal de Instrucción de San Martín N° 1'
    ],
    'FTU - Justicia Federal de Tucumán': [
        'Cámara Federal de Apelaciones de Tucumán',
        'Juzgado Federal de Tucumán N° 1',
        'Juzgado Federal de Instrucción de Tucumán N° 1'
    ]
};